export const skinColors = ['614335', 'ae5d29', 'd08b5b', 'edb98a', 'ffdbb4']

export const avatarChoices = {
  accessories: [
    {title: '(none)', value: 'none'},
    {title: 'Eye patch', value: 'eyepatch'},
    {title: 'Glasses 1', value: 'prescription01'},
    {title: 'Glasses 2', value: 'prescription02'},
    {title: 'Glasses 3', value: 'round'},
    {title: 'Sunglasses 1', value: 'sunglasses'},
    {title: 'Sunglasses 2', value: 'wayfarers'},
    {title: 'Sunglasses 3', value: 'kurt'},
  ],

  clothing: [
    {title: '(none)', value: 'none'},
    {title: 'Blazer & Shirt', value: 'blazerAndShirt'},
    {title: 'Blazer & Sweater', value: 'blazerAndSweater'},
    {title: 'Collar & Sweater', value: 'collarAndSweater'},
    {title: 'Hoodie', value: 'hoodie'},
    {title: 'Overall', value: 'overall'},
    {title: 'Shirt with Crew Neck', value: 'shirtCrewNeck'},
    {title: 'Shirt with Scoop Neck', value: 'shirtScoopNeck'},
    {title: 'Shirt with V Neck', value: 'shirtVNeck'},
  ],

  eyebrows: [
    {title: '(none)', value: 'none'},
    {title: 'Angry', value: 'angryNatural'},
    {title: 'Default', value: 'defaultNatural'},
    {title: 'Flat', value: 'flatNatural'},
    {title: 'Frown', value: 'frownNatural'},
    {title: 'Raised', value: 'raisedExcitedNatural'},
    {title: 'Sad', value: 'sadConcernedNatural'},
    {title: 'Up & Down', value: 'upDownNatural'},
  ],

  eyes: [
    {title: 'Closed', value: 'closed'},
    {title: 'Crying', value: 'cry'},
    {title: 'Default', value: 'default'},
    {title: 'Dizzy', value: 'xDizzy'},
    {title: 'Happy', value: 'happy'},
    {title: 'Rolling', value: 'eyeRoll'},
    {title: 'Side', value: 'side'},
    {title: 'Squinting', value: 'squint'},
    {title: 'Surprised', value: 'surprised'},
    {title: 'Winking', value: 'wink'},
    {title: 'Winking wackily', value: 'winkWacky'},
  ],

  facialHair: [
    {title: '(none)', value: 'none'},
    {title: 'Beard, light', value: 'beardLight'},
    {title: 'Beard, majestic', value: 'beardMajestic'},
    {title: 'Beard, medium', value: 'beardMedium'},
    {title: 'Moustache, fancy', value: 'moustacheFancy'},
    {title: 'Moustache, Magnum', value: 'moustacheMagnum'},
  ],

  mouth: [
    {title: 'Concerned', value: 'concerned'},
    {title: 'Default', value: 'default'},
    {title: 'Eating', value: 'eating'},
    {title: 'Grimace', value: 'grimace'},
    {title: 'Sad', value: 'sad'},
    {title: 'Screaming', value: 'screamOpen'},
    {title: 'Serious', value: 'serious'},
    {title: 'Slight Smile', value: 'twinkle'},
    {title: 'Smiling', value: 'smile'},
    {title: 'Tongue', value: 'tongue'},
  ],

  top: [
    {title: '(none)', value: 'none'},
    {title: 'Big Hair', value: 'bigHair'},
    {title: 'Bob', value: 'bob'},
    {title: 'Bun', value: 'bun'},
    {title: 'Curly', value: 'curly'},
    {title: 'Curvy', value: 'curvy'},
    {title: 'Dreads 1', value: 'dreads'},
    {title: 'Dreads 2', value: 'dreads01'},
    {title: 'Dreads 3', value: 'dreads02'},
    {title: 'Frida', value: 'frida'},
    {title: 'Frizzle', value: 'frizzle'},
    {title: 'Fro', value: 'fro'},
    {title: 'Fro & Headband', value: 'froBand'},
    {title: 'Hat', value: 'hat'},
    {title: 'Hijab', value: 'hijab'},
    {title: 'Long, but not too long', value: 'longButNotTooLong'},
    {title: 'Mia Wallace', value: 'miaWallace'},
    {title: 'Shaggy', value: 'shaggy'},
    {title: 'Shaggy & Mullet', value: 'shaggyMullet'},
    {title: 'Shaved Sides', value: 'shavedSides'},
    {title: 'Short & Curly', value: 'shortCurly'},
    {title: 'Short & Flat', value: 'shortFlat'},
    {title: 'Short & Round', value: 'shortRound'},
    {title: 'Short & Waved', value: 'shortWaved'},
    {title: 'Sides', value: 'sides'},
    {title: 'Straight 1', value: 'straight01'},
    {title: 'Straight 2', value: 'straight02'},
    {title: 'Straight 3', value: 'straightAndStrand'},
    {title: 'The Caesar', value: 'theCaesar'},
    {title: 'Turban', value: 'turban'},
    {title: 'Winter Hat 1', value: 'winterHat1'},
    {title: 'Winter Hat 2', value: 'winterHat02'},
    {title: 'Winter Hat 3', value: 'winterHat03'},
    {title: 'Winter Hat 4', value: 'winterHat04'},
  ],
}
