/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppHeader: typeof import('./components/app/AppHeader.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Event: typeof import('./components/Event.vue')['default']
    MiniColorPicker: typeof import('./components/MiniColorPicker.vue')['default']
    Participant: typeof import('./components/Participant.vue')['default']
    Plot: typeof import('./components/Plot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
